### PR TITLE
updated installer to install from the new location

### PR DESCRIPTION
**Pull request by vaibhav-kaushal**
updated installer to install from the new location

### CODE REVIEW

**Comment by olegabr** [comment]
According to this: https://github.com/qcubed/qcubed/blob/master/composer.json#L6 the correct package type for the `qcubed` itself is `qcubed-framework`. So, better revert this PR.

**Comment by vaibhav-kaushal** [comment]
It worked.

**Comment by vaibhav-kaushal** [comment]
If what you are saying is correct, I am not sure why it did!?

**Comment by olegabr** [comment]
Do not know. Just wander if it would work without this change?

**Comment by spekary** [comment]
This depends completely on how composer uses it, and composer changes all the time. Perhaps composer is ignoring it? I recommend keeping it as "qcubed-framework". From the documentation, it is supposed to be "vendor-type", and the type shouldn't be "qcubed". I think stating that the type is a "framework" is clearer.

**Comment by vaibhav-kaushal** [comment]
@spekary I understand. But it is not working without it. I too read the documentation and it says, it searches for _type_ but that's something which is not working and since it concerns installation, I'd say we should solve it asap.

**Comment by spekary** [comment]
That is strange. It certainly isn't working as documented. Will need to take a look at the composer source code to see why.

**Pull request merged**
